# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DemoPluginDockWidget
                                 A QGIS plugin
 Plugin demostración
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-20
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Fernando
        email                : fgomezdev@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'demo_plugin_dockwidget_base.ui'))


class DemoPluginDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(DemoPluginDockWidget, self).__init__(parent)
        self.setupUi(self)
        
        plugin_dir  = os.path.abspath(os.path.dirname(__file__)).replace("\\", "/")
        qss_path = os.path.join(plugin_dir, 'styles.qss')

        print(qss_path)
        with open(qss_path, 'r') as f:
            _style = f.read()
            self.setStyleSheet(_style)

        self.btn_prueba.clicked.connect(self.btn_prueba_clicked)
        self.btn_prueba.setStyleSheet('QPushButton {background-color: blue;}')

    def btn_prueba_clicked(self):
        self.lbl_mensaje.setText("Se ha presionado el botón...")



    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
